language: python
python:
  - "3.7"
# command to install dependencies
before_install:
  - export BOTO_CONFIG=/dev/null
  - pip install flake8
install:
  - pip install -r requirements.txt
  # This is a workaround for issue: https://github.com/spulec/moto/issues/1941
  - pip install -e git+https://github.com/spulec/moto@master#egg=moto
# command to run tests
script:
  - make flake8
  - make test